# Generated by Django 5.0.1 on 2026-04-03 05:20

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIGeneratorSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Midjourney v5', 'DALL-E 3'", max_length=100
                    ),
                ),
                (
                    "generator_type",
                    models.CharField(
                        choices=[
                            ("image", "Image Generator"),
                            ("video", "Video Generator"),
                            ("audio", "Audio Generator"),
                            ("manipulation", "Manipulation Tool"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "typical_resolutions",
                    models.JSONField(
                        help_text="List of common resolutions, e.g., ['1024x1024', '512x512']"
                    ),
                ),
                (
                    "noise_pattern",
                    models.JSONField(
                        help_text="Expected noise distribution characteristics"
                    ),
                ),
                (
                    "color_signature",
                    models.JSONField(
                        help_text="RGB histogram patterns characteristic of this generator"
                    ),
                ),
                (
                    "compression_artifacts",
                    models.TextField(
                        help_text="Description of characteristic compression artifacts"
                    ),
                ),
                (
                    "ela_threshold_min",
                    models.FloatField(help_text="Minimum ELA score for this generator"),
                ),
                (
                    "ela_threshold_max",
                    models.FloatField(help_text="Maximum ELA score for this generator"),
                ),
                (
                    "metadata_patterns",
                    models.JSONField(
                        help_text="Expected metadata patterns (e.g., missing EXIF, software signatures)"
                    ),
                ),
                (
                    "key_indicators",
                    models.JSONField(
                        default=list,
                        help_text="List of key visual indicators for this generator",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "AI Generator Signature",
                "verbose_name_plural": "AI Generator Signatures",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ForensicDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                        ],
                        max_length=10,
                    ),
                ),
                ("first_seen", models.DateField()),
                ("usage_count", models.IntegerField(default=1)),
                ("context", models.TextField()),
                (
                    "known_campaigns",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "threat_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Forensic Database Entry",
                "verbose_name_plural": "Forensic Database Entries",
            },
        ),
        migrations.CreateModel(
            name="MediaScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to=core.models.upload_path
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("url", "Social Media URL"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Social media URL if applicable",
                        null=True,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "scan_result",
                    models.CharField(
                        choices=[
                            ("real", "Real"),
                            ("fake", "Fake"),
                            ("manipulated", "Manipulated"),
                            ("suspicious", "Suspicious"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="AI confidence percentage (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "trust_score",
                    models.IntegerField(
                        help_text="Trust score (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "forensic_match",
                    models.BooleanField(
                        default=False, help_text="Found in historical database"
                    ),
                ),
                ("forensic_first_seen", models.DateField(blank=True, null=True)),
                ("forensic_usage_count", models.IntegerField(default=0)),
                ("forensic_context", models.TextField(blank=True, null=True)),
                (
                    "heatmap_data",
                    models.JSONField(
                        default=dict, help_text="Heatmap coordinates for visualization"
                    ),
                ),
                (
                    "analysis_details",
                    models.JSONField(
                        default=dict, help_text="Detailed analysis metrics"
                    ),
                ),
                (
                    "processing_time",
                    models.FloatField(help_text="Processing time in seconds"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Media Scan",
                "verbose_name_plural": "Media Scans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForensicAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ela_score",
                    models.FloatField(
                        blank=True,
                        help_text="ELA manipulation score (0-100)",
                        null=True,
                    ),
                ),
                (
                    "ela_heatmap_data",
                    models.JSONField(
                        blank=True,
                        help_text="ELA difference map for visualization",
                        null=True,
                    ),
                ),
                ("has_exif", models.BooleanField(default=False)),
                (
                    "exif_data",
                    models.JSONField(
                        blank=True, help_text="Extracted EXIF metadata", null=True
                    ),
                ),
                (
                    "metadata_consistency",
                    models.CharField(
                        choices=[
                            ("consistent", "Consistent"),
                            ("inconsistent", "Inconsistent"),
                            ("missing", "Missing"),
                        ],
                        default="missing",
                        max_length=20,
                    ),
                ),
                (
                    "software_detected",
                    models.CharField(
                        blank=True,
                        help_text="Software signatures found (e.g., 'Photoshop', 'GIMP')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "noise_uniformity",
                    models.FloatField(
                        blank=True,
                        help_text="Noise uniformity score (0-1, higher = more uniform)",
                        null=True,
                    ),
                ),
                (
                    "noise_pattern_anomalies",
                    models.JSONField(
                        blank=True,
                        help_text="List of detected noise anomalies",
                        null=True,
                    ),
                ),
                ("compression_artifacts_detected", models.BooleanField(default=False)),
                ("double_compression", models.BooleanField(default=False)),
                (
                    "compression_quality_estimate",
                    models.CharField(
                        blank=True,
                        help_text="Estimated compression quality (e.g., '95', '85')",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "color_histogram_score",
                    models.FloatField(
                        blank=True, help_text="Color anomaly score (0-100)", null=True
                    ),
                ),
                (
                    "color_anomalies",
                    models.JSONField(
                        blank=True,
                        help_text="Detected color distribution anomalies",
                        null=True,
                    ),
                ),
                (
                    "detected_sources",
                    models.JSONField(
                        blank=True,
                        help_text="List of detected AI generators with confidence scores",
                        null=True,
                    ),
                ),
                (
                    "primary_source",
                    models.CharField(
                        blank=True,
                        help_text="Most likely AI generator source",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "source_confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Confidence in primary source detection (0-100)",
                        null=True,
                    ),
                ),
                (
                    "manipulation_indicators",
                    models.JSONField(
                        default=list,
                        help_text="List of all detected manipulation indicators",
                    ),
                ),
                ("analysis_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "scan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forensic_analysis",
                        to="core.mediascan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forensic Analysis Result",
                "verbose_name_plural": "Forensic Analysis Results",
                "ordering": ["-analysis_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ReportedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url_or_file_name", models.CharField(max_length=500)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("url", "Social Media URL"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Why this content is being reported"),
                ),
                (
                    "reporter_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("additional_info", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("verified_fake", "Verified as Fake"),
                            ("verified_real", "Verified as Real"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("moderator_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.mediascan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reported Content",
                "verbose_name_plural": "Reported Content",
                "ordering": ["-created_at"],
            },
        ),
    ]
