# Generated by Django 6.0.3 on 2026-05-31 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mediascan_user_alter_mediascan_scan_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_question', models.CharField(choices=[('pet_name', "What was your first pet's name?"), ('mother_maiden', "What is your mother's maiden name?"), ('first_school', 'What was the name of your first school?'), ('favorite_teacher', 'Who was your favorite teacher?'), ('birth_city', 'In which city were you born?')], help_text='Select a recovery question only you know the answer to.', max_length=64)),
                ('security_answer_hash', models.CharField(help_text='Hashed answer for the chosen security question.', max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Security Profile',
                'verbose_name_plural': 'User Security Profiles',
            },
        ),
    ]
